onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /test_cpu/clk_tb
add wave -noupdate /test_cpu/reset_tb
add wave -noupdate /test_cpu/Din_tb
add wave -noupdate /test_cpu/output_tb
add wave -noupdate /test_cpu/z_tb
add wave -noupdate /test_cpu/N_tb
add wave -noupdate /test_cpu/o_tb
add wave -noupdate /test_cpu/uut/Din
add wave -noupdate /test_cpu/uut/clk
add wave -noupdate /test_cpu/uut/reset
add wave -noupdate /test_cpu/uut/output
add wave -noupdate /test_cpu/uut/Z_flag
add wave -noupdate /test_cpu/uut/N_flag
add wave -noupdate /test_cpu/uut/O_flag
add wave -noupdate /test_cpu/uut/clk_out
add wave -noupdate /test_cpu/uut/instr
add wave -noupdate /test_cpu/uut/state
add wave -noupdate /test_cpu/uut/Upc
add wave -noupdate /test_cpu/uut/wren
add wave -noupdate /test_cpu/uut/reada
add wave -noupdate /test_cpu/uut/readb
add wave -noupdate /test_cpu/uut/uinst
add wave -noupdate /test_cpu/uut/flag
add wave -noupdate /test_cpu/uut/bypass
add wave -noupdate /test_cpu/uut/add_en
add wave -noupdate /test_cpu/uut/d_en
add wave -noupdate /test_cpu/uut/ins
add wave -noupdate /test_cpu/uut/z
add wave -noupdate /test_cpu/uut/n_f
add wave -noupdate /test_cpu/uut/o
add wave -noupdate /test_cpu/uut/address
add wave -noupdate /test_cpu/uut/data
add wave -noupdate /test_cpu/uut/current_instruction
add wave -noupdate /test_cpu/uut/sign_ex
add wave -noupdate /test_cpu/uut/sign
add wave -noupdate /test_cpu/uut/offset
add wave -noupdate /test_cpu/uut/addr
add wave -noupdate /test_cpu/uut/A0/clk_in
add wave -noupdate /test_cpu/uut/A0/clk_out
add wave -noupdate /test_cpu/uut/A0/tmp
add wave -noupdate /test_cpu/uut/A0/count
add wave -noupdate /test_cpu/uut/A1/instr
add wave -noupdate /test_cpu/uut/A1/clk
add wave -noupdate /test_cpu/uut/A1/reset
add wave -noupdate /test_cpu/uut/A1/state
add wave -noupdate /test_cpu/uut/A1/PC_out
add wave -noupdate /test_cpu/uut/A1/uPC
add wave -noupdate /test_cpu/uut/A1/next_uPC
add wave -noupdate /test_cpu/uut/A1/pres_state
add wave -noupdate /test_cpu/uut/A2/inst
add wave -noupdate /test_cpu/uut/A2/flag
add wave -noupdate /test_cpu/uut/A2/upc
add wave -noupdate /test_cpu/uut/A2/reset
add wave -noupdate /test_cpu/uut/A2/wren
add wave -noupdate /test_cpu/uut/A2/reada
add wave -noupdate /test_cpu/uut/A2/readb
add wave -noupdate /test_cpu/uut/A2/uinst
add wave -noupdate /test_cpu/uut/A2/bypass
add wave -noupdate /test_cpu/uut/A2/address_en
add wave -noupdate /test_cpu/uut/A2/data_en
add wave -noupdate /test_cpu/uut/A3/Ins
add wave -noupdate /test_cpu/uut/A3/offset
add wave -noupdate /test_cpu/uut/A3/Din
add wave -noupdate /test_cpu/uut/A3/Bypass
add wave -noupdate /test_cpu/uut/A3/address_en
add wave -noupdate /test_cpu/uut/A3/data_en
add wave -noupdate /test_cpu/uut/A3/clk
add wave -noupdate /test_cpu/uut/A3/Z_flag
add wave -noupdate /test_cpu/uut/A3/n_flag
add wave -noupdate /test_cpu/uut/A3/o_flag
add wave -noupdate /test_cpu/uut/A3/address
add wave -noupdate /test_cpu/uut/A3/data
add wave -noupdate /test_cpu/uut/A3/Qa_in
add wave -noupdate /test_cpu/uut/A3/Qb_in
add wave -noupdate /test_cpu/uut/A3/sum_in
add wave -noupdate /test_cpu/uut/A3/mux
add wave -noupdate /test_cpu/uut/A3/mux_A
add wave -noupdate /test_cpu/uut/A3/mux_b
add wave -noupdate /test_cpu/uut/A3/waddr
add wave -noupdate /test_cpu/uut/A3/ra
add wave -noupdate /test_cpu/uut/A3/rb
add wave -noupdate /test_cpu/uut/A3/write_en
add wave -noupdate /test_cpu/uut/A3/reada
add wave -noupdate /test_cpu/uut/A3/readb
add wave -noupdate /test_cpu/uut/A3/Zfl
add wave -noupdate /test_cpu/uut/A3/nfl
add wave -noupdate /test_cpu/uut/A3/ofl
add wave -noupdate /test_cpu/uut/A3/u1/wd
add wave -noupdate /test_cpu/uut/A3/u1/waddr
add wave -noupdate /test_cpu/uut/A3/u1/ra
add wave -noupdate /test_cpu/uut/A3/u1/rb
add wave -noupdate /test_cpu/uut/A3/u1/wren
add wave -noupdate /test_cpu/uut/A3/u1/reada
add wave -noupdate /test_cpu/uut/A3/u1/readb
add wave -noupdate /test_cpu/uut/A3/u1/reset
add wave -noupdate /test_cpu/uut/A3/u1/clk
add wave -noupdate /test_cpu/uut/A3/u1/Qa
add wave -noupdate /test_cpu/uut/A3/u1/Qb
add wave -noupdate -expand /test_cpu/uut/A3/u1/r
add wave -noupdate /test_cpu/uut/A3/u2/op
add wave -noupdate /test_cpu/uut/A3/u2/a
add wave -noupdate /test_cpu/uut/A3/u2/b
add wave -noupdate /test_cpu/uut/A3/u2/y
add wave -noupdate /test_cpu/uut/A3/u2/z_flag
add wave -noupdate /test_cpu/uut/A3/u2/n_flag
add wave -noupdate /test_cpu/uut/A3/u2/o_flag
add wave -noupdate /test_cpu/uut/A3/u2/en
add wave -noupdate /test_cpu/uut/A3/u2/reset
add wave -noupdate /test_cpu/uut/A3/u2/temp
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {927 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 219
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {236 ns}
